tools:
    php_code_sniffer: true
    php_cpd: true
    php_loc: true
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
filter:
    paths: [src/*]
checks:
    php:
        code_rating: true
        duplication: true
